src/main/default/objects/Quiz_Settings__mdt/Quiz_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Quiz Settings</label>
    <pluralLabel>Quiz Settings</pluralLabel>
</CustomObject>

src/main/default/objects/Quiz_Settings__mdt/fields/Player_App_URL__c.field-meta.xml
<CustomField>
    <fullName>Player_App_URL__c</fullName>
    <label>Player App URL</label>
    <type>Url</type>
</CustomField>

src/main/default/objects/Quiz_Settings__mdt/fields/Player_App_URL_Minified__c.field-meta.xml
<CustomField>
    <fullName>Player_App_URL_Minified__c</fullName>
    <label>Player App URL Minified</label>
    <type>Url</type>
</CustomField>

src/main/default/objects/Quiz_Settings__mdt/fields/Question_Timer__c.field-meta.xml
<CustomField>
    <fullName>Question_Timer__c</fullName>
    <defaultValue>12</defaultValue>
    <inlineHelpText>Duration of question phase in seconds</inlineHelpText>
    <label>Question Timer</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Quiz_Settings__mdt/fields/Quiz_API_Key__c.field-meta.xml
<CustomField>
    <fullName>Quiz_API_Key__c</fullName>
    <label>Quiz API Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/classes/QuizSettings.cls
global with sharing class QuizSettings {
    @AuraEnabled
    global Id id { get; set; }
    @AuraEnabled
    global String playerAppUrl { get; set; }
    @AuraEnabled
    global String playerAppUrlMinified { get; set; }
    @AuraEnabled
    global String quizApiKey { get; set; }
    @AuraEnabled
    global Decimal questionTimer { get; set; }

    global QuizSettings() {
    }

    global QuizSettings(Quiz_Settings__mdt settings) {
        this.id = settings.Id;
        this.playerAppUrl = settings.Player_App_URL__c;
        this.playerAppUrlMinified = settings.Player_App_URL_Minified__c;
        this.quizApiKey = settings.Quiz_API_Key__c;
        this.questionTimer = settings.Question_Timer__c;
    }
}