src/main/default/objects/Quiz_Settings__mdt/Quiz_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Quiz Settings</label>
    <pluralLabel>Quiz Settings</pluralLabel>
</CustomObject>

src/main/default/objects/Quiz_Settings__mdt/fields/Player_App_URL__c.field-meta.xml
<CustomField>
    <fullName>Player_App_URL__c</fullName>
    <label>Player App URL</label>
    <type>Url</type>
</CustomField>

src/main/default/objects/Quiz_Settings__mdt/fields/Player_App_URL_Minified__c.field-meta.xml
<CustomField>
    <fullName>Player_App_URL_Minified__c</fullName>
    <label>Player App URL Minified</label>
    <type>Url</type>
</CustomField>

src/main/default/objects/Quiz_Settings__mdt/fields/Quiz_API_Key__c.field-meta.xml
<CustomField>
    <fullName>Quiz_API_Key__c</fullName>
    <label>Quiz API Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/classes/QuizSettingsService.cls
public class QuizSettingsService extends QuizAbstractDataService {
    public Quiz_Settings__mdt get() {
        return (Quiz_Settings__mdt) getSingleRecord(
            [
                SELECT
                    Id,
                    Player_App_URL__c,
                    Player_App_URL_Minified__c,
                    Quiz_API_Key__c
                FROM Quiz_Settings__mdt
            ]
        );
    }
}