src/main/default/objects/Quiz_Player__c/Quiz_Player__c.object-meta.xml
<CustomObject>
    <label>Quiz Player</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Player__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Ranking</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Quiz_Player__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <summarizedField>Quiz_Answer__c.Score__c</summarizedField>
    <summaryForeignKey>Quiz_Answer__c.Player__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/classes/QuizPlayer.cls
global with sharing class QuizPlayer {
    @AuraEnabled
    global Id id { get; set; }
    @AuraEnabled
    global String name { get; set; }
    @AuraEnabled
    global Decimal score { get; set; }
    @AuraEnabled
    global Decimal rank { get; set; }

    global QuizPlayer() {
    }

    global QuizPlayer(Quiz_Player__c player) {
        this.id = player.Id;
        this.name = player.Name;
        this.score = player.Score__c;
        this.rank = player.Ranking__c;
    }

    global static List<QuizPlayer> fromRecordList(
        List<Quiz_Player__c> records
    ) {
        List<QuizPlayer> players = new List<QuizPlayer>();
        for (Quiz_Player__c record : records) {
            players.add(new QuizPlayer(record));
        }
        return players;
    }
}