src/main/default/objects/Quiz_Player__c/Quiz_Player__c.object-meta.xml
<CustomObject>
    <label>Quiz Player</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Player__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Ranking</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/test/default/classes/PlayerServiceTest.cls
@isTest
public with sharing class PlayerServiceTest {
    @isTest static void onlyPlayerRanksOne() {
        Quiz_Player__c player1 = QuizSessionTestFactory.createQuizPlayer('1');
        PlayerService playerService = new PlayerService();
        playerService.assignRanking();
        List<Quiz_Player__c> updatedPlayers = [SELECT ID, Ranking__c FROM Quiz_Player__c];

        System.assertEquals(1, updatedPlayers.size());
        System.assertEquals(1, updatedPlayers[0].Ranking__c);
    }

    @isTest static void twoPlayersSameScoreBothRankOne() {
        Quiz_Player__c player1 = QuizSessionTestFactory.createQuizPlayerWithScore('one', 100);
        Quiz_Player__c player2 = QuizSessionTestFactory.createQuizPlayerWithScore('two', 100);
        PlayerService playerService = new PlayerService();
        playerService.assignRanking();

        Integer ranking1 = [SELECT Id, Ranking__c FROM Quiz_Player__c WHERE Id = :player1.Id].Ranking__c.intValue();
        Integer ranking2 = [SELECT Id, Ranking__c FROM Quiz_Player__c WHERE Id = :player2.Id].Ranking__c.intValue();

        System.assertEquals(1, ranking1);
        System.assertEquals(1, ranking2);
    }

    @isTest static void twoPlayersDifferentScoreDifferentRanking() {
        Quiz_Player__c player1 = QuizSessionTestFactory.createQuizPlayerWithScore('one', 100);
        Quiz_Player__c player2 = QuizSessionTestFactory.createQuizPlayerWithScore('two', 50);
        PlayerService playerService = new PlayerService();
        playerService.assignRanking();

        Integer ranking1 = [SELECT Id, Ranking__c FROM Quiz_Player__c WHERE Id = :player1.Id].Ranking__c.intValue();
        Integer ranking2 = [SELECT Id, Ranking__c FROM Quiz_Player__c WHERE Id = :player2.Id].Ranking__c.intValue();

        System.assertEquals(1, ranking1);
        System.assertEquals(2, ranking2);
    }    

    @isTest static void threePlayersMixedRanking() {
        Quiz_Player__c player1 = QuizSessionTestFactory.createQuizPlayerWithScore('one', 100);
        Quiz_Player__c player2 = QuizSessionTestFactory.createQuizPlayerWithScore('two', 100);
        Quiz_Player__c player3 = QuizSessionTestFactory.createQuizPlayerWithScore('three', 10);
        PlayerService playerService = new PlayerService();
        playerService.assignRanking();

        Integer ranking1 = [SELECT Id, Ranking__c FROM Quiz_Player__c WHERE Id = :player1.Id].Ranking__c.intValue();
        Integer ranking2 = [SELECT Id, Ranking__c FROM Quiz_Player__c WHERE Id = :player2.Id].Ranking__c.intValue();
        Integer ranking3 = [SELECT Id, Ranking__c FROM Quiz_Player__c WHERE Id = :player3.Id].Ranking__c.intValue();

        System.assertEquals(1, ranking1);
        System.assertEquals(1, ranking2);
        System.assertEquals(2, ranking3);
    }        
}