src/main/default/objects/Quiz_Player__c/Quiz_Player__c.object-meta.xml
<CustomObject>
    <label>Quiz Player</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Question__c/Quiz_Question__c.object-meta.xml
<CustomObject>
    <label>Quiz Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Session__c/Quiz_Session__c.object-meta.xml
<CustomObject>
    <label>Quiz Session</label>
    <nameField>
        <displayFormat>QS-{0000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Session__c/fields/Current_Question__c.field-meta.xml
<CustomField>
    <fullName>Current_Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Current Question</label>
    <referenceTo>Quiz_Question__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Quiz_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/test/default/classes/QuizAnswerServiceTest.cls
@isTest(isParallel=true)
public class QuizAnswerServiceTest {
    @isTest
    static void getAnswerStats_works() {
        QuizAnswerService service = new QuizAnswerService();
        Quiz_Session__c session = QuizSessionTestFactory.createQuizSession();
        Quiz_Question__c question = session.Current_Question__r;
        List<Quiz_Player__c> players = QuizSessionTestFactory.createQuizPlayers(
            2
        );
        QuizSessionTestFactory.createQuizAnswer(
            players[0].Id,
            question.Id,
            'B'
        );
        QuizSessionTestFactory.createQuizAnswer(
            players[1].Id,
            question.Id,
            'D'
        );

        Test.startTest();
        Map<String, Integer> stats = service.getAnswerStats();
        Test.stopTest();

        System.assertEquals(0, stats.get('A'));
        System.assertEquals(1, stats.get('B'));
        System.assertEquals(0, stats.get('C'));
        System.assertEquals(1, stats.get('D'));
    }
}