src/main/default/objects/Quiz_Answer__c/Quiz_Answer__c.object-meta.xml
<CustomObject>
    <label>Quiz Answer</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>Answer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quiz_Answer</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Quiz_Answer__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player</label>
    <referenceTo>Quiz_Player__c</referenceTo>
    <relationshipLabel>Quiz Answers</relationshipLabel>
    <relationshipName>Quiz_Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quiz_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question</label>
    <referenceTo>Quiz_Question__c</referenceTo>
    <relationshipLabel>Quiz Answers</relationshipLabel>
    <relationshipName>Quiz_Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quiz_Session__c/Quiz_Session__c.object-meta.xml
<CustomObject>
    <label>Quiz Session</label>
    <nameField>
        <displayFormat>QS-{0000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Session__c/fields/Current_Question__c.field-meta.xml
<CustomField>
    <fullName>Current_Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Current Question</label>
    <referenceTo>Quiz_Question__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Quiz_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quiz_Session__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quiz_Phase</valueSetName>
    </valueSet>
</CustomField>

src/main/default/globalValueSets/Quiz_Answer.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>a</fullName>
    </customValue>
    <customValue>
        <fullName>b</fullName>
    </customValue>
    <customValue>
        <fullName>c</fullName>
    </customValue>
    <customValue>
        <fullName>d</fullName>
    </customValue>
    <masterLabel>Quiz Answer</masterLabel>
</GlobalValueSet>

src/main/default/globalValueSets/Quiz_Phase.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Registration</fullName>
        <default>true</default>
        <label>Registration</label>
    </customValue>
    <customValue>
        <fullName>PreQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>Question</fullName>
    </customValue>
    <customValue>
        <fullName>PostQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>QuestionResults</fullName>
    </customValue>
    <customValue>
        <fullName>GameResults</fullName>
    </customValue>
    <masterLabel>Quiz Phase</masterLabel>
</GlobalValueSet>

src/main/default/classes/AnswerService.cls
public class AnswerService extends AbstractDataService {

    private static QuizSessionService sessionService = new QuizSessionService();

    public Quiz_Answer__c create(Id playerId, String answer) {
        // Check game phase and question
        Quiz_Session__c session = sessionService.getQuizSession();
        if (session.Phase__c != QuizSessionService.Phase.Question.name()) {
            throw new InvalidPhaseException();
        }
        Id questionId = session.Current_Question__c;

        // Check for duplicate answer from player
        try {
            getFromPlayer(playerId, questionId);
            throw new DuplicateAnswerException();
        } catch (NoRecordFoundException e) {}

        // Save answer
        Quiz_Answer__c answerRecord = new Quiz_Answer__c(Player__c = playerId, Question__c = questionId, Answer__c=  answer);
        insert answerRecord;
        return answerRecord;
    }

    public Quiz_Answer__c getFromPlayer(Id playerId, Id questionId) {
        return (Quiz_Answer__c) getSingleRecord([SELECT Id, Player__c, Question__c, Answer__c FROM Quiz_Answer__c WHERE Player__c = :playerId AND Question__c = :questionId]);
    }

    public class InvalidPhaseException extends Exception {}
    public class DuplicateAnswerException extends Exception {}
}