src/main/default/objects/Quiz_Answer__c/Quiz_Answer__c.object-meta.xml
<CustomObject>
    <label>Quiz Answer</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>Answer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Player__c/Quiz_Player__c.object-meta.xml
<CustomObject>
    <label>Quiz Player</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Question__c/Quiz_Question__c.object-meta.xml
<CustomObject>
    <label>Quiz Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Question__c/fields/Correct_Answer__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer__c</fullName>
    <label>Correct Answer</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quiz_Answer</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Quiz_Session__c/Quiz_Session__c.object-meta.xml
<CustomObject>
    <label>Quiz Session</label>
    <nameField>
        <displayFormat>QS-{0000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Session__c/fields/Current_Question__c.field-meta.xml
<CustomField>
    <fullName>Current_Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Current Question</label>
    <referenceTo>Quiz_Question__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Quiz_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quiz_Session__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quiz_Phase</valueSetName>
    </valueSet>
</CustomField>

src/main/default/globalValueSets/Quiz_Answer.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>a</fullName>
    </customValue>
    <customValue>
        <fullName>b</fullName>
    </customValue>
    <customValue>
        <fullName>c</fullName>
    </customValue>
    <customValue>
        <fullName>d</fullName>
    </customValue>
    <masterLabel>Quiz Answer</masterLabel>
</GlobalValueSet>

src/main/default/globalValueSets/Quiz_Phase.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Registration</fullName>
        <default>true</default>
        <label>Registration</label>
    </customValue>
    <customValue>
        <fullName>PreQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>Question</fullName>
    </customValue>
    <customValue>
        <fullName>PostQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>QuestionResults</fullName>
    </customValue>
    <customValue>
        <fullName>GameResults</fullName>
    </customValue>
    <masterLabel>Quiz Phase</masterLabel>
</GlobalValueSet>

src/test/default/classes/QuizSessionTriggerHelperTest.cls
@isTest(isParallel=true)
public class QuizSessionTriggerHelperTest {
    private static String PHASE_REGISTRATION = QuizSessionService.Phase.Registration.name(),
        PHASE_QUESTION = QuizSessionService.Phase.Question.name(),
        PHASE_QUESTION_RESULTS = QuizSessionService.Phase.QuestionResults.name();

    @isTest
    static void changePhaseToRegistrationResetsCurrentQuestion() {
        Test.setMock(
            HttpCalloutMock.class,
            new TestUtils.MockSuccessHttpResponse()
        );

        Quiz_Session__c quizSession = QuizSessionTestFactory.createQuizSession();
        Quiz_Question__c question1 = quizSession.Current_Question__r;
        Quiz_Question__c question2 = QuizSessionTestFactory.createQuizQuestion();
        QuizSessionTestFactory.createQuizSessionQuestion(
            quizSession,
            question2,
            1
        );

        quizSession.Current_Question__r = question2;
        quizSession.Phase__c = PHASE_QUESTION;
        update quizSession;

        quizSession.Phase__c = PHASE_REGISTRATION;
        update quizSession;

        Quiz_Session__c updatedSession = [
            SELECT Current_Question__c
            FROM Quiz_Session__c
        ];
        System.assertEquals(question1.Id, updatedSession.Current_Question__c);
    }

    @isTest
    static void changePhaseToRegistrationRemovesPlayersAndAnswers() {
        Test.setMock(
            HttpCalloutMock.class,
            new TestUtils.MockSuccessHttpResponse()
        );

        Quiz_Session__c quizSession = QuizSessionTestFactory.createQuizSession();
        Quiz_Question__c question = quizSession.Current_Question__r;
        Quiz_Player__c player = QuizSessionTestFactory.createQuizPlayers(1)[0];
        Quiz_Answer__c quizAnswer = QuizSessionTestFactory.createQuizAnswer(
            player.Id,
            question.Id,
            question.Correct_Answer__c
        );

        // change to Registration from non-Registration phase
        quizSession.Phase__c = PHASE_QUESTION;
        update quizSession;

        Test.startTest();
        quizSession.Phase__c = PHASE_REGISTRATION;
        update quizSession;
        Test.stopTest();

        Integer playerCount = [SELECT COUNT() FROM Quiz_Player__c];
        Integer answerCount = [SELECT COUNT() FROM Quiz_Answer__c];
        System.assertEquals(0, playerCount);
        System.assertEquals(0, answerCount);
    }
}