src/main/default/objects/Quiz_Answer__c/Quiz_Answer__c.object-meta.xml
<CustomObject>
    <label>Quiz Answer</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>Answer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Answer__c/fields/IsCorrect__c.field-meta.xml
<CustomField>
    <fullName>IsCorrect__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCorrect</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Quiz_Answer__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Score for the given player and question.</description>
    <inlineHelpText>Score for the given player and question.</inlineHelpText>
    <label>Score</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Quiz_Answer__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Timestamp</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Quiz_Question__c/Quiz_Question__c.object-meta.xml
<CustomObject>
    <label>Quiz Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Session__c/Quiz_Session__c.object-meta.xml
<CustomObject>
    <label>Quiz Session</label>
    <nameField>
        <displayFormat>QS-{0000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Session__c/fields/Current_Question__c.field-meta.xml
<CustomField>
    <fullName>Current_Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Current Question</label>
    <referenceTo>Quiz_Question__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Quiz_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quiz_Session__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quiz_Phase</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Quiz_Settings__mdt/Quiz_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Quiz Settings</label>
    <pluralLabel>Quiz Settings</pluralLabel>
</CustomObject>

src/main/default/objects/Quiz_Settings__mdt/fields/Player_App_URL__c.field-meta.xml
<CustomField>
    <fullName>Player_App_URL__c</fullName>
    <label>Player App URL</label>
    <type>Url</type>
</CustomField>

src/main/default/objects/Quiz_Settings__mdt/fields/Quiz_API_Key__c.field-meta.xml
<CustomField>
    <fullName>Quiz_API_Key__c</fullName>
    <label>Quiz API Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/globalValueSets/Quiz_Phase.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Registration</fullName>
        <default>true</default>
        <label>Registration</label>
    </customValue>
    <customValue>
        <fullName>PreQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>Question</fullName>
    </customValue>
    <customValue>
        <fullName>PostQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>QuestionResults</fullName>
    </customValue>
    <customValue>
        <fullName>GameResults</fullName>
    </customValue>
    <masterLabel>Quiz Phase</masterLabel>
</GlobalValueSet>

src/main/default/classes/QuizSessionHelper.cls
public with sharing class QuizSessionHelper {
    private static final String PHASE_REGISTRATION = QuizSessionService.Phase.Registration.name(),
        PHASE_PRE_QUESTION = QuizSessionService.Phase.PreQuestion.name(),
        PHASE_QUESTION = QuizSessionService.Phase.Question.name(),
        PHASE_QUESTION_RESULTS = QuizSessionService.Phase.QuestionResults.name(),
        PHASE_GAME_RESULTS = QuizSessionService.Phase.GameResults.name();

    private static final QuizSettingsService settingsService = new QuizSettingsService();
    private static final QuizSessionService sessionService = new QuizSessionService();

    // When curAnswerTimestamp == minAnswerTimestamp, score = 1000
    // With curAnswerTimestamp == maxAnswerTimestamp, score = 500
    @TestVisible
    private Long computeScore(
        Decimal curAnswerTimestamp,
        Decimal minAnswerTimestamp,
        Decimal minMaxTimestampDelta
    ) {
        // If one or zero answer, award full points (avoids zero division)
        if (minMaxTimestampDelta == 0) {
            return 1000;
        }

        Decimal delayFromFastestAnswer =
            curAnswerTimestamp - minAnswerTimestamp;
        // Calulate speed factor: 0 = fastest, 1 = slowest
        Decimal speedFactor = delayFromFastestAnswer / minMaxTimestampDelta;
        return (Long) (1000 * (1.00 - (speedFactor / 2.00)));
    }

    public void updatePlayerScores(Id sessionId) {
        // Get current question
        Quiz_Session__c session = sessionService.getQuizSession(sessionId);
        Quiz_Question__c currentQuestion = sessionService.getCurrentQuestion(
            session.Id
        );

        // Get correct answers
        QuizAnswerService answerService = new QuizAnswerService();
        List<Quiz_Answer__c> answers = answerService.getCorrectAnswers(
            currentQuestion
        );
        if (answers.isEmpty()) {
            return;
        }

        // Get answer min and max timestamps
        Decimal minTimestamp = answers[0].Timestamp__c;
        Decimal maxTimestamp = answers[answers.size() - 1].Timestamp__c;
        Decimal timestampDelta = maxTimestamp - minTimestamp;

        // Compute and assign scores
        for (Quiz_Answer__c answer : answers) {
            // Score correct answer
            Long score = computeScore(
                answer.Timestamp__c,
                minTimestamp,
                timestampDelta
            );
            answer.IsCorrect__c = true;
            answer.Score__c = score;
        }
        update answers;

        // Refresh ranks
        QuizPlayerService playerService = new QuizPlayerService();
        playerService.assignRanks(session.Id);
    }

    public Quiz_Session__c triggerNextPhase(Id sessionId) {
        Quiz_Session__c session = sessionService.getQuizSession(sessionId);

        if (session.Phase__c == PHASE_REGISTRATION) {
            session.Phase__c = PHASE_PRE_QUESTION;
        } else if (session.Phase__c == PHASE_PRE_QUESTION) {
            session.Phase__c = PHASE_QUESTION;
        } else if (session.Phase__c == PHASE_QUESTION) {
            session.Phase__c = PHASE_QUESTION_RESULTS;
            updatePlayerScores(session.Id);
        } else if (session.Phase__c == PHASE_QUESTION_RESULTS) {
            List<Quiz_Question__c> questions = sessionService.getSessionQuestions(
                sessionId
            );
            Integer currentQuestionIndex = this.getCurrentQuestionIndex(
                session,
                questions
            );
            // Last question, show game results
            if (currentQuestionIndex == questions.size() - 1) {
                session.Phase__c = PHASE_GAME_RESULTS;
            } else {
                // Move to next question
                session.Phase__c = PHASE_PRE_QUESTION;
                Quiz_Question__c nextQuestion = questions[
                    currentQuestionIndex + 1
                ];
                session.Current_Question__c = nextQuestion.Id;
            }
        } else if (session.Phase__c == PHASE_GAME_RESULTS) {
            session.Phase__c = PHASE_REGISTRATION;
        } else {
            throw new InvalidPhaseException(
                'Unsupported quiz phase: ' + session.Phase__c
            );
        }

        update session;
        // Push phase change to player app
        QuizSessionHelper.pushPhaseUpdateToPlayerApp(
            session.Id,
            session.Phase__c
        );
        return session;
    }

    public Quiz_Session__c resetSession(Id sessionId) {
        // Reset session
        Quiz_Session__c session = sessionService.getQuizSession(sessionId);
        session.Phase__c = PHASE_REGISTRATION;
        // Reset current question
        List<Quiz_Question__c> questions = sessionService.getSessionQuestions(
            session.Id
        );
        if (questions.size() > 0) {
            session.Current_Question__c = questions[0].Id;
        }
        update session;
        // Delete all players and answers
        QuizPlayerService playerService = new QuizPlayerService();
        playerService.deletePlayers(session.Id);
        // Push phase change to player app
        QuizSessionHelper.pushPhaseUpdateToPlayerApp(
            session.Id,
            session.Phase__c
        );
        return session;
    }

    private Integer getCurrentQuestionIndex(
        Quiz_Session__c session,
        List<Quiz_Question__c> questions
    ) {
        Integer currentQuestionIndex = -1;
        for (
            Integer i = 0;
            currentQuestionIndex == -1 &&
            i < questions.size();
            i++
        ) {
            if (session.Current_Question__c == questions[i].Id) {
                currentQuestionIndex = i;
            }
        }
        return currentQuestionIndex;
    }

    @future(callout=true)
    public static void pushPhaseUpdateToPlayerApp(Id sessionId, String phase) {
        Quiz_Settings__mdt settings = settingsService.get();

        HttpRequest request = new HttpRequest();
        request.setMethod('PUT');
        request.setEndpoint(
            settings.Player_App_URL__c +
            '/api/quiz-sessions/' +
            sessionId
        );
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Api-Key', settings.Quiz_Api_Key__c);
        request.setBody('{ "phase": "' + phase + '" }');

        Http httpClient = new Http();
        HttpResponse response = httpClient.send(request);
        if (response.getStatusCode() != 200) {
            throw new QuizPhasePushException(
                'Failed to push quiz phase update: HTTP' +
                response.getStatusCode() +
                ' ' +
                response.getBody()
            );
        }
    }

    public class QuizPhasePushException extends Exception {
    }

    public class InvalidPhaseException extends Exception {
    }
}