src/main/default/objects/Quiz_Answer__c/Quiz_Answer__c.object-meta.xml
<CustomObject>
    <label>Quiz Answer</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>Answer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Answer__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Score for the given player and question.</description>
    <inlineHelpText>Score for the given player and question.</inlineHelpText>
    <label>Score</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Quiz_Player__c/Quiz_Player__c.object-meta.xml
<CustomObject>
    <label>Quiz Player</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Player__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Ranking</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Quiz_Player__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <summarizedField>Quiz_Answer__c.Score__c</summarizedField>
    <summaryForeignKey>Quiz_Answer__c.Player__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/classes/PlayerService.cls
public class PlayerService extends AbstractDataService  {

    public Quiz_Player__c getFromName(String name) {
        return (Quiz_Player__c) getSingleRecord([SELECT Id FROM Quiz_Player__c WHERE Name = :name]);
    }

    public Quiz_Player__c create(String name) {
        Quiz_Player__c player = new Quiz_Player__c(Name = name);
        insert player;
        return player;
    }

    public List<Quiz_Player__c> getPlayersSortedByScore(Integer maxFetchCount) {
        String query = 'SELECT Id, Name, Score__c FROM Quiz_Player__c ORDER BY Score__c DESC';
        if (maxFetchCount != null) {
            query += ' LIMIT ' + maxFetchCount;
        } 

        return Database.query(query);
    }

    public Map<ID, Quiz_Player__c> getPlayers() {
        return new Map<ID, Quiz_Player__c>([SELECT Id, Score__c FROM Quiz_Player__c]);
    }

    public void deleteAnswersAndPlayers() {
        // need delete answers before delete players
        List<Quiz_Answer__c> answers = [SELECT ID FROM Quiz_Answer__c];
        delete answers;

        List<Quiz_Player__c> players = [SELECT ID FROM Quiz_Player__c];
        delete players;
    }

    public void assignRanking() {
        List<Quiz_Player__c> updatedPlayers = getPlayersSortedByScore(null);
        if (updatedPlayers.isEmpty()) {
            return;
        } else {
            // assign first place, regardless of how many records
            updatedPlayers[0].Ranking__c = 1;
            if (updatedPlayers.size() == 1) {
                update updatedPlayers;
                return;
            }
        }

        Integer ranking = 1;
        for (Integer i = 1; i < updatedPlayers.size(); i++) {
            // if previous score differs from current score, increment ranking
            if (updatedPlayers[i-1].Score__c < updatedPlayers[i].Score__c) {
                ranking += 1;
            }
                
            updatedPlayers[i].Ranking__c = ranking;
        }

        update updatedPlayers;        
    }
}