src/main/default/objects/Quiz_Answer__c/Quiz_Answer__c.object-meta.xml
<CustomObject>
    <label>Quiz Answer</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>Answer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quiz_Answer</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Quiz_Answer__c/fields/IsCorrect__c.field-meta.xml
<CustomField>
    <fullName>IsCorrect__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCorrect</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Quiz_Answer__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player</label>
    <referenceTo>Quiz_Player__c</referenceTo>
    <relationshipLabel>Quiz Answers</relationshipLabel>
    <relationshipName>Quiz_Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quiz_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question</label>
    <referenceTo>Quiz_Question__c</referenceTo>
    <relationshipLabel>Quiz Answers</relationshipLabel>
    <relationshipName>Quiz_Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quiz_Answer__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Score for the given player and question.</description>
    <inlineHelpText>Score for the given player and question.</inlineHelpText>
    <label>Score</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Quiz_Answer__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Timestamp</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Quiz_Player__c/Quiz_Player__c.object-meta.xml
<CustomObject>
    <label>Quiz Player</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Player__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Ranking</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Quiz_Player__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <summarizedField>Quiz_Answer__c.Score__c</summarizedField>
    <summaryForeignKey>Quiz_Answer__c.Player__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/Quiz_Session__c/Quiz_Session__c.object-meta.xml
<CustomObject>
    <label>Quiz Session</label>
    <nameField>
        <displayFormat>QS-{0000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Session__c/fields/Current_Question__c.field-meta.xml
<CustomField>
    <fullName>Current_Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Current Question</label>
    <referenceTo>Quiz_Question__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Quiz_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quiz_Session__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quiz_Phase</valueSetName>
    </valueSet>
</CustomField>

src/main/default/globalValueSets/Quiz_Answer.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>a</fullName>
    </customValue>
    <customValue>
        <fullName>b</fullName>
    </customValue>
    <customValue>
        <fullName>c</fullName>
    </customValue>
    <customValue>
        <fullName>d</fullName>
    </customValue>
    <masterLabel>Quiz Answer</masterLabel>
</GlobalValueSet>

src/main/default/globalValueSets/Quiz_Phase.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Registration</fullName>
        <default>true</default>
        <label>Registration</label>
    </customValue>
    <customValue>
        <fullName>PreQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>Question</fullName>
    </customValue>
    <customValue>
        <fullName>PostQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>QuestionResults</fullName>
    </customValue>
    <customValue>
        <fullName>GameResults</fullName>
    </customValue>
    <masterLabel>Quiz Phase</masterLabel>
</GlobalValueSet>

src/main/default/classes/QuizAnswerService.cls
public class QuizAnswerService extends QuizAbstractDataService {
    private static final QuizSessionService sessionService = new QuizSessionService();
    private static final QuizPlayerService playerService = new QuizPlayerService();

    public PlayerStats getPlayerAnswerStats(Id playerId) {
        List<Quiz_Answer__c> allAnswersFromPlayer = [
            SELECT Player__c, Score__c, IsCorrect__c
            FROM Quiz_Answer__c
            WHERE Player__c = :playerId
        ];
        Integer correctCount = 0;
        for (Quiz_Answer__c answerRes : allAnswersFromPlayer) {
            if (answerRes.IsCorrect__c) {
                correctCount++;
            }
        }

        Quiz_Player__c player = playerService.getFromId(playerId);
        Integer totalCount = allAnswersFromPlayer.size();
        return new PlayerStats(
            totalCount - correctCount,
            correctCount,
            totalCount,
            player.Score__c,
            player.Ranking__c.intValue(),
            player.Name
        );
    }

    public Map<String, Integer> getAnswerMap() {
        // Check game phase and question
        Quiz_Session__c session = sessionService.getQuizSession();
        Id questionId = session.Current_Question__c;
        Map<String, Integer> answerMap = new Map<String, Integer>();
        List<AggregateResult> answerCount = [
            SELECT Answer__c, COUNT(Id)
            FROM Quiz_Answer__c
            WHERE Question__c = :questionId
            GROUP BY Answer__c
        ];
        for (AggregateResult answerRes : answerCount) {
            answerMap.put(
                answerRes.get('Answer__c').toString(),
                Integer.valueOf(answerRes.get('expr0'))
            );
        }

        return answerMap;
    }

    public Quiz_Answer__c create(Id playerId, String answer) {
        // Check game phase and question
        Quiz_Session__c session = sessionService.getQuizSession();
        if (session.Phase__c != QuizSessionService.Phase.Question.name()) {
            throw new InvalidPhaseException();
        }
        Id questionId = session.Current_Question__c;

        // Check for duplicate answer from player
        try {
            getFromPlayer(playerId, questionId);
            throw new DuplicateAnswerException();
        } catch (NoRecordFoundException e) {
        }

        // Save answer
        Quiz_Answer__c answerRecord = new Quiz_Answer__c(
            Player__c = playerId,
            Question__c = questionId,
            Answer__c = answer
        );
        insert answerRecord;
        return answerRecord;
    }

    public Set<Id> getUniquePlayerIds(List<Quiz_Answer__c> answers) {
        Set<Id> playerIds = new Set<Id>();
        for (Quiz_Answer__c answer : answers) {
            if (!playerIds.contains(answer.Player__c)) {
                playerIds.add(answer.Player__c);
            }
        }
        return playerIds;
    }

    public Map<Id, Id> getPlayerQuestionMapping(Set<Id> playerIds) {
        Map<Id, Id> mapPlayerQuestion = new Map<Id, Id>();
        List<Quiz_Answer__c> allAnswers = [
            SELECT Id, Player__c, Question__c
            FROM Quiz_Answer__c
            WHERE Player__c IN :playerIds
            FOR UPDATE
        ];
        for (Quiz_Answer__c answer : allAnswers) {
            mapPlayerQuestion.put(answer.Player__c, answer.Question__c);
        }
        return mapPlayerQuestion;
    }

    public List<Quiz_Answer__c> getAnswersOfPlayerIdsAndQuestionId(
        Set<Id> playerIds,
        Id questionId
    ) {
        // get answers ordered by oldest records first: Id values are created in ascending order
        return [
            SELECT Id, Player__c, Question__c, Answer__c, Timestamp__c, Score__c
            FROM Quiz_Answer__c
            WHERE Player__c IN :playerIds AND Question__c = :questionId
            ORDER BY Id ASC
        ];
    }

    public Quiz_Answer__c getFromPlayer(Id playerId, Id questionId) {
        return (Quiz_Answer__c) getSingleRecord(
            [
                SELECT Id, Player__c, Question__c, Answer__c, Score__c
                FROM Quiz_Answer__c
                WHERE Player__c = :playerId AND Question__c = :questionId
            ]
        );
    }

    public class InvalidPhaseException extends Exception {
    }
    public class DuplicateAnswerException extends Exception {
    }
    public class UnknownUserException extends Exception {
    }

    public class PlayerStats {
        @AuraEnabled
        public Integer wrongCount;
        @AuraEnabled
        public Integer correctCount;
        @AuraEnabled
        public Integer totalCount;
        @AuraEnabled
        public Decimal score;
        @AuraEnabled
        public Integer rank;
        @AuraEnabled
        public String name;

        public PlayerStats(
            Integer wrongCount,
            Integer correctCount,
            Integer totalCount,
            Decimal score,
            Integer rank,
            String name
        ) {
            this.wrongCount = wrongCount;
            this.correctCount = correctCount;
            this.totalCount = totalCount;
            this.score = score;
            this.rank = rank;
            this.name = name;
        }
    }
}