src/main/default/objects/Quiz_Answer__c/Quiz_Answer__c.object-meta.xml
<CustomObject>
    <label>Quiz Answer</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>Answer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Answer__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Score for the given player and question.</description>
    <inlineHelpText>Score for the given player and question.</inlineHelpText>
    <label>Score</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Quiz_Player__c/Quiz_Player__c.object-meta.xml
<CustomObject>
    <label>Quiz Player</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Player__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <summarizedField>Quiz_Answer__c.Score__c</summarizedField>
    <summaryForeignKey>Quiz_Answer__c.Player__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/Quiz_Question__c/Quiz_Question__c.object-meta.xml
<CustomObject>
    <label>Quiz Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Question__c/fields/Correct_Answer__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer__c</fullName>
    <label>Correct Answer</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quiz_Answer</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Quiz_Session__c/Quiz_Session__c.object-meta.xml
<CustomObject>
    <label>Quiz Session</label>
    <nameField>
        <displayFormat>QS-{0000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Session__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quiz_Phase</valueSetName>
    </valueSet>
</CustomField>

src/main/default/globalValueSets/Quiz_Answer.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>a</fullName>
    </customValue>
    <customValue>
        <fullName>b</fullName>
    </customValue>
    <customValue>
        <fullName>c</fullName>
    </customValue>
    <customValue>
        <fullName>d</fullName>
    </customValue>
    <masterLabel>Quiz Answer</masterLabel>
</GlobalValueSet>

src/main/default/globalValueSets/Quiz_Phase.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Registration</fullName>
        <default>true</default>
        <label>Registration</label>
    </customValue>
    <customValue>
        <fullName>PreQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>Question</fullName>
    </customValue>
    <customValue>
        <fullName>PostQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>QuestionResults</fullName>
    </customValue>
    <customValue>
        <fullName>GameResults</fullName>
    </customValue>
    <masterLabel>Quiz Phase</masterLabel>
</GlobalValueSet>

src/test/default/classes/QuizSessionHelperTest.cls
@isTest 
public with sharing class QuizSessionHelperTest {
    
    @isTest static void quizSessionStartsWithRegistration() {
        Quiz_Session__c quizSession = QuizSessionTestFactory.createQuizSession();
        List<Quiz_Question__c> questions = new List<Quiz_Question__c>();

        questions = [SELECT Id FROM Quiz_Question__c];
        System.assert(questions.size() > 0);
        System.assertEquals('Registration', quizSession.Phase__c);
    }

    @isTest static void playerCreatedWithZeroScore() {
        List<Quiz_Player__c> players = new List<Quiz_Player__c>();
        Quiz_Player__c player1 = QuizSessionTestFactory.createQuizPlayer();

        players = [SELECT Id FROM Quiz_Player__c];
        System.assert(players.size() > 0);
        System.assertEquals(0, player1.Score__c);
    }      

    @isTest static void updateScoreOnPlayerWithFullMarks() {
        Quiz_Session__c quizSession = QuizSessionTestFactory.createQuizSession();
        Quiz_Question__c question = [SELECT Id, Correct_Answer__c FROM Quiz_Question__c LIMIT 1];        
        Quiz_Player__c player = QuizSessionTestFactory.createQuizPlayer();

        Test.startTest();
        quizSession.Phase__c = 'PostQuestion';
        Quiz_Answer__c quizAnswer = QuizSessionTestFactory.createQuizAnswer(player.Id, question.Id, question.Correct_Answer__c); 
        update quizSession;
        Test.stopTest();   

        System.assertEquals('PostQuestion', quizSession.Phase__c);
        Integer score = [SELECT Id, Score__c FROM Quiz_Player__c WHERE ID = :player.Id LIMIT 1].Score__c.intValue();
        System.assertEquals(1000, score);
    }

    @isTest static void updateScoreOnAnswerWithFullMarks() {
        Quiz_Session__c quizSession = QuizSessionTestFactory.createQuizSession();
        Quiz_Question__c question = [SELECT Id, Correct_Answer__c FROM Quiz_Question__c LIMIT 1];        
        Quiz_Player__c player = QuizSessionTestFactory.createQuizPlayer();

        Test.startTest();
        quizSession.Phase__c = 'PostQuestion';
        Quiz_Answer__c quizAnswer = QuizSessionTestFactory.createQuizAnswer(player.Id, question.Id, question.Correct_Answer__c); 
        update quizSession;
        Test.stopTest();   

        System.assertEquals('PostQuestion', quizSession.Phase__c);
        Integer score = [SELECT Id, Score__c FROM Quiz_Answer__c WHERE ID = :quizAnswer.Id LIMIT 1].Score__c.intValue();
        System.assertEquals(1000, score);
    }    

    @isTest static void doNotUpdatePlayerScoreIfAnswerWrong() {
        Quiz_Session__c quizSession = QuizSessionTestFactory.createQuizSession();
        Quiz_Question__c question = [SELECT Id, Correct_Answer__c FROM Quiz_Question__c LIMIT 1];        
        Quiz_Player__c player = QuizSessionTestFactory.createQuizPlayer();

        Test.startTest();
        quizSession.Phase__c = 'PostQuestion';
        Quiz_Answer__c quizAnswer = QuizSessionTestFactory.createQuizAnswer(player.Id, question.Id, 'a'); 
        update quizSession;
        Test.stopTest();   

        System.assertEquals('PostQuestion', quizSession.Phase__c);
        Integer score = [SELECT Id, Score__c FROM Quiz_Player__c WHERE ID = :player.Id LIMIT 1].Score__c.intValue();
        System.assertEquals(0, score);
    }

    @isTest static void doNotUpdateAnswerScoreIfAnswerWrong() {
        Quiz_Session__c quizSession = QuizSessionTestFactory.createQuizSession();
        Quiz_Question__c question = [SELECT Id, Correct_Answer__c FROM Quiz_Question__c LIMIT 1];        
        Quiz_Player__c player = QuizSessionTestFactory.createQuizPlayer();

        Test.startTest();
        quizSession.Phase__c = 'PostQuestion';
        Quiz_Answer__c quizAnswer = QuizSessionTestFactory.createQuizAnswer(player.Id, question.Id, 'a'); 
        update quizSession;
        Test.stopTest();        

        System.assertEquals('PostQuestion', quizSession.Phase__c);
        Integer score = [SELECT Id, Score__c FROM Quiz_Answer__c WHERE ID = :quizAnswer.Id LIMIT 1].Score__c.intValue();
        System.assertEquals(0, score);
    }        
}