src/main/default/objects/Quiz_Answer__c/Quiz_Answer__c.object-meta.xml
<CustomObject>
    <label>Quiz Answer</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>Answer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Answer__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player</label>
    <referenceTo>Quiz_Player__c</referenceTo>
    <relationshipLabel>Quiz Answers</relationshipLabel>
    <relationshipName>Quiz_Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quiz_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question</label>
    <referenceTo>Quiz_Question__c</referenceTo>
    <relationshipLabel>Quiz Answers</relationshipLabel>
    <relationshipName>Quiz_Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quiz_Answer__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Timestamp</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/classes/QuizAnswerTriggerHelper.cls
public with sharing class QuizAnswerTriggerHelper {
    public static void beforeInsert(List<Quiz_Answer__c> newAnswers) {
        QuizAnswerService answerService = new QuizAnswerService();
        Set<Id> playerIds = answerService.getUniquePlayerIds(newAnswers);
        Map<Id, Id> mapPlayerQuestion = answerService.getPlayerQuestionMapping(
            playerIds
        );
        for (Quiz_Answer__c answer : newAnswers) {
            String key = answer.Player__c;
            if (
                mapPlayerQuestion.containsKey(key) &&
                mapPlayerQuestion.get(key) == answer.Question__c
            ) {
                answer.addError('Duplicate answer');
            } else {
                // # of milliseconds since January 1, 1970, 00:00:00 GMT, ie. 1569261277045
                answer.Timestamp__c = Datetime.now().getTime();
            }
        }
    }
}