src/main/default/objects/Quiz_Answer__c/Quiz_Answer__c.object-meta.xml
<CustomObject>
    <label>Quiz Answer</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>Answer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Answer__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Player</label>
    <referenceTo>Quiz_Player__c</referenceTo>
    <relationshipLabel>Quiz Answers</relationshipLabel>
    <relationshipName>Quiz_Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quiz_Player__c/Quiz_Player__c.object-meta.xml
<CustomObject>
    <label>Quiz Player</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Question__c/Quiz_Question__c.object-meta.xml
<CustomObject>
    <label>Quiz Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Question__c/fields/Correct_Answer__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer__c</fullName>
    <label>Correct Answer</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quiz_Answer</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Quiz_Session__c/Quiz_Session__c.object-meta.xml
<CustomObject>
    <label>Quiz Session</label>
    <nameField>
        <displayFormat>QS-{0000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Session__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quiz_Phase</valueSetName>
    </valueSet>
</CustomField>

src/main/default/globalValueSets/Quiz_Answer.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>a</fullName>
    </customValue>
    <customValue>
        <fullName>b</fullName>
    </customValue>
    <customValue>
        <fullName>c</fullName>
    </customValue>
    <customValue>
        <fullName>d</fullName>
    </customValue>
    <masterLabel>Quiz Answer</masterLabel>
</GlobalValueSet>

src/main/default/globalValueSets/Quiz_Phase.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Registration</fullName>
        <default>true</default>
        <label>Registration</label>
    </customValue>
    <customValue>
        <fullName>PreQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>Question</fullName>
    </customValue>
    <customValue>
        <fullName>PostQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>QuestionResults</fullName>
    </customValue>
    <customValue>
        <fullName>GameResults</fullName>
    </customValue>
    <masterLabel>Quiz Phase</masterLabel>
</GlobalValueSet>

src/test/default/classes/AnswerServiceTest.cls
@isTest
public with sharing class AnswerServiceTest {
    private static String QUESTION = QuizSessionService.Phase.Question.name();

    @isTest static void getFromPlayerThrowsNoRecordFoundException() {    
        AnswerService answerService = new AnswerService();
        Quiz_Question__c question = QuizSessionTestFactory.createQuizQuestion();        
        Quiz_Player__c player = QuizSessionTestFactory.createQuizPlayer('1');
        try {
            answerService.getFromPlayer(player.Id, question.Id);
            System.assert(false);
        } catch(AbstractDataService.NoRecordFoundException e) {}       

        Integer answerCount = [SELECT COUNT() FROM Quiz_Answer__c];        
        System.assertEquals(0, answerCount);
    }

    @isTest static void duplicateCallsToCreateFails() {    
        Quiz_Session__c quizSession = QuizSessionTestFactory.createQuizSession();
        quizSession.Phase__c = QUESTION;
        update quizSession;
        AnswerService answerService = new AnswerService();
        Quiz_Question__c question = [SELECT Id, Correct_Answer__c FROM Quiz_Question__c LIMIT 1];        
        Quiz_Player__c player = QuizSessionTestFactory.createQuizPlayer('1');
        try {
            answerService.create(player.Id, question.Correct_Answer__c);
            answerService.create(player.Id, question.Correct_Answer__c);
        } catch(AnswerService.DuplicateAnswerException e) {}
        
        Integer answerCount = [SELECT COUNT() FROM Quiz_Answer__c];        
        System.assertEquals(1, answerCount);
    }    
    
    @isTest static void getAfterCreateReturnsRecord() {    
        Quiz_Session__c quizSession = QuizSessionTestFactory.createQuizSession();
        quizSession.Phase__c = QUESTION;
        update quizSession;
        AnswerService answerService = new AnswerService();
        Quiz_Question__c question = [SELECT Id, Correct_Answer__c FROM Quiz_Question__c LIMIT 1];        
        Quiz_Player__c player = QuizSessionTestFactory.createQuizPlayer('1');
        try {
            answerService.create(player.Id, question.Correct_Answer__c);
            Quiz_Answer__c quizAnswer = answerService.getFromPlayer(player.Id, question.Id);            
            System.assert(quizAnswer.Player__c == player.Id);
        } catch(AnswerService.DuplicateAnswerException e) {}     
    }        
}