src/main/default/objects/Quiz_Answer__c/Quiz_Answer__c.object-meta.xml
<CustomObject>
    <label>Quiz Answer</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>Answer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Player__c/Quiz_Player__c.object-meta.xml
<CustomObject>
    <label>Quiz Player</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Question__c/Quiz_Question__c.object-meta.xml
<CustomObject>
    <label>Quiz Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Question__c/fields/Correct_Answer__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer__c</fullName>
    <label>Correct Answer</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quiz_Answer</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Quiz_Session__c/Quiz_Session__c.object-meta.xml
<CustomObject>
    <label>Quiz Session</label>
    <nameField>
        <displayFormat>QS-{0000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Session__c/fields/Current_Question__c.field-meta.xml
<CustomField>
    <fullName>Current_Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Current Question</label>
    <referenceTo>Quiz_Question__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Quiz_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quiz_Session__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quiz_Phase</valueSetName>
    </valueSet>
</CustomField>

src/main/default/globalValueSets/Quiz_Answer.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>a</fullName>
    </customValue>
    <customValue>
        <fullName>b</fullName>
    </customValue>
    <customValue>
        <fullName>c</fullName>
    </customValue>
    <customValue>
        <fullName>d</fullName>
    </customValue>
    <masterLabel>Quiz Answer</masterLabel>
</GlobalValueSet>

src/main/default/globalValueSets/Quiz_Phase.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Registration</fullName>
        <default>true</default>
        <label>Registration</label>
    </customValue>
    <customValue>
        <fullName>PreQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>Question</fullName>
    </customValue>
    <customValue>
        <fullName>PostQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>QuestionResults</fullName>
    </customValue>
    <customValue>
        <fullName>GameResults</fullName>
    </customValue>
    <masterLabel>Quiz Phase</masterLabel>
</GlobalValueSet>

src/test/default/classes/QuizControllerTest.cls
@isTest(isParallel=true)
public class QuizControllerTest {
    private static String PHASE_REGISTRATION = QuizSessionService.Phase.Registration.name();
    private static String PHASE_QUESTION = QuizSessionService.Phase.Question.name();

    @isTest
    static void getWinnerStats_works() {
        Quiz_Session__c session = QuizSessionTestFactory.createQuizSession();
        Quiz_Player__c player = QuizSessionTestFactory.createQuizPlayers(1)[0];

        Test.startTest();
        QuizAnswerService.PlayerStats stats = QuizController.getWinnerStats();
        Test.stopTest();
    }

    @isTest
    static void getWinnerStats_failsWhenNoPlayers() {
        try {
            QuizController.getWinnerStats();
            // expect to fail
            System.assert(false);
        } catch (AuraHandledException e) {
            System.assert(true);
        }
    }

    @isTest
    static void getPlayerAnswerStats_works() {
        Quiz_Session__c session = QuizSessionTestFactory.createQuizSession();
        Quiz_Player__c player = QuizSessionTestFactory.createQuizPlayers(1)[0];

        Test.startTest();
        QuizController.getPlayerAnswerStats(player.Id);
        Test.stopTest();
    }

    @isTest
    static void getPlayerAnswerStats_failsWhenMissingPlayerId() {
        try {
            QuizController.getPlayerAnswerStats(null);
            // expect to fail
            System.assert(false);
        } catch (AuraHandledException e) {
            System.assert(true);
        }
    }

    @isTest
    static void getPlayerAnswerStats_failsWhenUnknownPlayerId() {
        Id fakePlayerId = QuizTestUtils.getFakeId(Quiz_Player__c.SObjectType);
        try {
            QuizController.getPlayerAnswerStats(fakePlayerId);
            // expect to fail
            System.assert(false);
        } catch (AuraHandledException e) {
            System.assert(true);
        }
    }

    @isTest
    static void resetGame_works() {
        Test.setMock(
            HttpCalloutMock.class,
            new QuizTestUtils.MockSuccessHttpResponse()
        );

        Quiz_Session__c session = QuizSessionTestFactory.createQuizSession();
        Quiz_Player__c player = QuizSessionTestFactory.createQuizPlayers(1)[0];
        Quiz_Question__c question1 = session.Current_Question__r;
        Quiz_Question__c question2 = QuizSessionTestFactory.createQuizQuestion();
        Quiz_Answer__c quizAnswer1 = QuizSessionTestFactory.createQuizAnswer(
            player.Id,
            question1.Id,
            question1.Correct_Answer__c
        );
        session.Phase__c = PHASE_QUESTION;
        session.Current_Question__r = question2;
        update session;

        Test.startTest();
        QuizController.resetGame();
        Test.stopTest();

        Integer playerCount = Database.countQuery(
            'SELECT COUNT() FROM Quiz_Player__c WITH SECURITY_ENFORCED'
        );
        System.assertEquals(0, playerCount);
        Integer answerCount = Database.countQuery(
            'SELECT COUNT() FROM Quiz_Answer__c WITH SECURITY_ENFORCED'
        );
        System.assertEquals(0, answerCount);
        QuizSessionService sessionService = new QuizSessionService();
        Quiz_Session__c updatedSession = sessionService.getQuizSession();
        System.assertEquals(PHASE_REGISTRATION, updatedSession.Phase__c);
        System.assertEquals(question1.Id, updatedSession.Current_Question__c);
    }
}