src/main/default/objects/Quiz_Question__c/Quiz_Question__c.object-meta.xml
<CustomObject>
    <label>Quiz Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Session__c/Quiz_Session__c.object-meta.xml
<CustomObject>
    <label>Quiz Session</label>
    <nameField>
        <displayFormat>QS-{0000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Session__c/fields/Current_Question__c.field-meta.xml
<CustomField>
    <fullName>Current_Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Current Question</label>
    <referenceTo>Quiz_Question__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Quiz_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quiz_Session__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quiz_Phase</valueSetName>
    </valueSet>
</CustomField>

src/main/default/globalValueSets/Quiz_Phase.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Registration</fullName>
        <default>true</default>
        <label>Registration</label>
    </customValue>
    <customValue>
        <fullName>PreQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>Question</fullName>
    </customValue>
    <customValue>
        <fullName>PostQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>QuestionResults</fullName>
    </customValue>
    <customValue>
        <fullName>GameResults</fullName>
    </customValue>
    <masterLabel>Quiz Phase</masterLabel>
</GlobalValueSet>

src/main/default/classes/QuizSessionTriggerHelper.cls
public with sharing class QuizSessionTriggerHelper {
    private static String PHASE_REGISTRATION = QuizSessionService.Phase.Registration.name(),
        PHASE_QUESTION_RESULTS = QuizSessionService.Phase.QuestionResults.name();

    public static void beforeUpdate(
        List<Quiz_Session__c> updatedSessions,
        Map<Id, Quiz_Session__c> oldSessions
    ) {
        for (Quiz_Session__c updatedSession : updatedSessions) {
            Quiz_Session__c oldSession = oldSessions.get(updatedSession.Id);
            // Is phase change to Registration
            if (
                oldSession.Phase__c != updatedSession.Phase__c &&
                updatedSession.Phase__c == PHASE_REGISTRATION
            ) {
                // Reset current question
                QuizSessionService quizSessionService = new QuizSessionService();
                List<Quiz_Question__c> questions = quizSessionService.getSessionQuestions(
                    updatedSession.Id
                );
                if (questions.size() > 0) {
                    updatedSession.Current_Question__c = questions[0].Id;
                }
            }
        }
    }

    public static void afterUpdate(
        List<Quiz_Session__c> updatedSessions,
        Map<Id, Quiz_Session__c> oldSessions
    ) {
        for (Quiz_Session__c updatedSession : updatedSessions) {
            Quiz_Session__c oldSession = oldSessions.get(updatedSession.Id);
            // Is phase change?
            if (oldSession.Phase__c != updatedSession.Phase__c) {
                // New phase is QuestionResult
                if (updatedSession.Phase__c == PHASE_QUESTION_RESULTS) {
                    // Compute players score
                    QuizSessionHelper quizSessionHelper = new QuizSessionHelper();
                    quizSessionHelper.updatePlayerScores();
                } else if (updatedSession.Phase__c == PHASE_REGISTRATION) {
                    // New phase is Registration
                    // Delete all players and answers
                    PlayerService playerService = new PlayerService();
                    playerService.deleteAnswersAndPlayers();
                }
            }
        }
    }
}