src/main/default/objects/Quiz_Question__c/Quiz_Question__c.object-meta.xml
<CustomObject>
    <label>Quiz Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Question__c/fields/Answer_A__c.field-meta.xml
<CustomField>
    <fullName>Answer_A__c</fullName>
    <label>Answer A</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Quiz_Question__c/fields/Answer_B__c.field-meta.xml
<CustomField>
    <fullName>Answer_B__c</fullName>
    <label>Answer B</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Quiz_Question__c/fields/Answer_C__c.field-meta.xml
<CustomField>
    <fullName>Answer_C__c</fullName>
    <label>Answer C</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Quiz_Question__c/fields/Answer_D__c.field-meta.xml
<CustomField>
    <fullName>Answer_D__c</fullName>
    <label>Answer D</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Quiz_Question__c/fields/Correct_Answer__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer__c</fullName>
    <label>Correct Answer</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quiz_Answer</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Quiz_Question__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/globalValueSets/Quiz_Answer.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>a</fullName>
    </customValue>
    <customValue>
        <fullName>b</fullName>
    </customValue>
    <customValue>
        <fullName>c</fullName>
    </customValue>
    <customValue>
        <fullName>d</fullName>
    </customValue>
    <masterLabel>Quiz Answer</masterLabel>
</GlobalValueSet>

src/main/default/classes/QuizQuestion.cls
global with sharing class QuizQuestion {
    @AuraEnabled
    global Id id { get; set; }
    @AuraEnabled
    global String label { get; set; }
    @AuraEnabled
    global String answerA { get; set; }
    @AuraEnabled
    global String answerB { get; set; }
    @AuraEnabled
    global String answerC { get; set; }
    @AuraEnabled
    global String answerD { get; set; }
    @AuraEnabled
    global String correctAnswer { get; set; }

    global QuizQuestion() {
    }

    global QuizQuestion(Quiz_Question__c question) {
        this.id = question.Id;
        this.label = question.Label__c;
        // Retrieve optional fields
        try {
            this.answerA = question.Answer_A__c;
            this.answerB = question.Answer_B__c;
            this.answerC = question.Answer_C__c;
            this.answerD = question.Answer_D__c;
            this.correctAnswer = question.Correct_Answer__c;
        } catch (Exception e) {
            // Do nothing if fields are not available
        }
    }

    global static List<QuizQuestion> fromRecordList(
        List<Quiz_Question__c> records
    ) {
        List<QuizQuestion> questions = new List<QuizQuestion>();
        for (Quiz_Question__c record : records) {
            questions.add(new QuizQuestion(record));
        }
        return questions;
    }
}