src/main/default/objects/Quiz_Question__c/Quiz_Question__c.object-meta.xml
<CustomObject>
    <label>Quiz Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Session__c/Quiz_Session__c.object-meta.xml
<CustomObject>
    <label>Quiz Session</label>
    <nameField>
        <displayFormat>QS-{0000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Session__c/fields/Current_Question__c.field-meta.xml
<CustomField>
    <fullName>Current_Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Current Question</label>
    <referenceTo>Quiz_Question__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Quiz_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quiz_Session__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Quiz_Phase</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Quiz_Session_Question__c/Quiz_Session_Question__c.object-meta.xml
<CustomObject>
    <label>Quiz Session Question</label>
    <nameField>
        <displayFormat>QSQ-{00000}</displayFormat>
        <label>Auto Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Session Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Session_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Quiz_Question__c</referenceTo>
    <relationshipLabel>Session</relationshipLabel>
    <relationshipName>Session</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/globalValueSets/Quiz_Phase.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Registration</fullName>
        <default>true</default>
        <label>Registration</label>
    </customValue>
    <customValue>
        <fullName>PreQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>Question</fullName>
    </customValue>
    <customValue>
        <fullName>PostQuestion</fullName>
    </customValue>
    <customValue>
        <fullName>QuestionResults</fullName>
    </customValue>
    <customValue>
        <fullName>GameResults</fullName>
    </customValue>
    <masterLabel>Quiz Phase</masterLabel>
</GlobalValueSet>

src/test/default/classes/QuizPostInstallScriptTest.cls
@isTest(isParallel=true)
public class QuizPostInstallScriptTest {
    private static final String PHASE_REGISTRATION = QuizSessionService.Phase.Registration.name();

    @isTest
    static void freshInstall_works() {
        Test.testInstall(new QuizPostInstallScript(), null);

        // Check for question
        List<Quiz_Question__c> questions = [SELECT Id FROM Quiz_Question__c];
        System.assertEquals(1, questions.size(), 'Question not found');
        Quiz_Question__c question = questions[0];
        // Check for session
        List<Quiz_Session__c> sessions = [
            SELECT Id, Phase__c, Current_Question__c
            FROM Quiz_Session__c
            WITH SECURITY_ENFORCED
        ];
        System.assertEquals(1, sessions.size(), 'Session not found');
        Quiz_Session__c session = sessions[0];
        System.assertEquals(PHASE_REGISTRATION, session.Phase__c);
        System.assertEquals(question.Id, session.Current_Question__c);
        // Check for session question
        List<Quiz_Session_Question__c> sessionQuestions = [
            SELECT Question__c
            FROM Quiz_Session_Question__c
            WITH SECURITY_ENFORCED
        ];
        System.assertEquals(
            1,
            sessionQuestions.size(),
            'Session question not found'
        );
        Quiz_Session_Question__c sessionQuestion = sessionQuestions[0];
        System.assertEquals(question.Id, sessionQuestion.Question__c);
    }
}