src/main/default/objects/Quiz_Question__c/Quiz_Question__c.object-meta.xml
<CustomObject>
    <label>Quiz Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quiz_Question__c/fields/Answer_A__c.field-meta.xml
<CustomField>
    <fullName>Answer_A__c</fullName>
    <label>Answer A</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Quiz_Question__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/test/default/classes/QuizQuestionTest.cls
@isTest(isParallel=true)
public class QuizQuestionTest {
    @isTest
    static void fromRecordList_works() {
        List<Quiz_Question__c> records = new List<Quiz_Question__c>{
            new Quiz_Question__c(Label__c = 'l1', Answer_A__c = 'aA')
        };

        List<QuizQuestion> questions = QuizQuestion.fromRecordList(records);

        System.assertEquals(records.size(), questions.size());
        System.assertEquals(records[0].Label__c, questions[0].label);
        System.assertEquals(records[0].Answer_A__c, questions[0].answerA);
    }
}